### ISSUE TITLE
how to set fqdn's value

### ISSUE THREAD

**Issue by jacktrane** [RobustPerception/PushProx#16]

**Comment by Conorbro** [comment]
There's a flag for the FQDN of the proxy when running the client: 

`./client --proxy-url=http://proxy:8080/`

As for the client, you set the FQDN in the Prometheus configuration file:

```
scrape_configs:
- job_name: node
  proxy_url: http://proxy:8080/
  static_configs:
    - targets: ['client:9100']  # Presuming the FQDN of the client is "client".
```
